version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: esbuild
    versions:
    - 0.11.12
    - 0.11.15
  - dependency-name: eslint-config-prettier
    versions:
    - 8.2.0
  - dependency-name: "@types/three"
    versions:
    - 0.127.1
